package com.isa.project.web.rest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.isa.project.bean.Visitor;
import com.isa.project.repository.VisitorRepository;

@Controller // This means that this class is a Controller
@RequestMapping(value = "/login")  // This means URL's start with /login (after Application path)
public class LoginController {

	// This means to get the bean called visitorRepository
    // Which is auto-generated by Spring, we will use it to handle the data	
	@Autowired
	private VisitorRepository visitorRepository;
	
	@RequestMapping(value = "")
	public String index(Model model) {
		
		
		return "login/login";
	}
	
	// @ResponseBody means the returned String is the response, not a view name
	// @RequestParam means it is a parameter from the GET or POST request

	@RequestMapping(value = "all", method =  RequestMethod.GET)
	public @ResponseBody Iterable<Visitor> getAllUsers() {
		
		
		return visitorRepository.findAll();
	}

}
